export enum ActionType {
    // Application state
    SET_ERROR = 'SET_ERROR',
    DISMISS_ERROR = 'DISMISS_ERROR',
    SET_CONNECTED = 'SET_CONNECTED',
    SET_NAME = 'SET_NAME',
    SET_CLIENT_ID = 'SET_CLIENT_ID',

    // Web Sockets
    WS_SEND_MESSAGE = 'WS_SEND_MESSAGE',
    WS_MESSAGE = 'WS_MESSAGE',
    WS_CONNECTED = 'WS_CONNECTED',
    WS_DISCONNECTED = 'WS_DISCONNECTED',

    // Incoming transfers
    ACCEPT_TRANSFER = 'ACCEPT_TRANSFER',
    REJECT_TRANSFER = 'REJECT_TRANSFER',
    ADD_INCOMING_TRANSFER = 'ADD_INCOMING_TRANSFER',
    REMOVE_INCOMING_TRANSFER = 'REMOVE_INCOMING_TRANSFER',
    MOVE_INCOMING_TRANSFER_TO_ACTIVE = 'MOVE_INCOMING_TRANSFER_TO_ACTIVE',

    // Outgoing transfers
    CREATE_TRANSFER = 'CREATE_TRANSFER',
    CANCEL_TRANSFER = 'CANCEL_TRANSFER',
    ADD_OUTGOING_TRANSFER = 'ADD_OUTGOING_TRANSFER',
    REMOVE_OUTGOING_TRANSFER = 'REMOVE_OUTGOING_TRANSFER',
    MOVE_OUTGOING_TRANSFER_TO_ACTIVE = 'MOVE_OUTGOING_TRANSFER_TO_ACTIVE',

    // Active transfers
    ADD_PEER_CONNECTION = 'ADD_PEER_CONNECTION',
    ADD_ICE_CANDIDATE = 'ADD_ICE_CANDIDATE',
    SET_LOCAL_DESCRIPTION = 'SET_LOCAL_DESCRIPTION',
    SET_REMOTE_DESCRIPTION = 'SET_REMOTE_DESCRIPTION',
    UPDATE_TRANSFER = 'UPDATE_TRANSFER',
};